# Site settings
author: Lauren Stone
title: Lauren Stone's Blog
header-img: img/home-bg.png
email: lstone321@gmail.com
copyright_name: Lauren Stone
description: > # this means to ignore newlines until "baseurl:"
  My Journey Learning Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  laurstone

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
